Add ConfirmInput interface specification
tonlabs/DeBot-IS-consortium pull request #17
Opened 2021-02-10 10:59 UTC by BigRoma

2021-02-12 12:25 UTC, sertony approved these changes

2021-02-15 12:11 UTC, Keshoid requested changes

2021-02-15 12:11 UTC, Keshoid commented on ConfirmInput/README.md
> +    prompt: bytes
```suggestion
	answerId: uint32 - id of function callback.
	prompt: bytes - utf-8 string to print to the user before input.
```

2021-02-15 12:11 UTC, Keshoid commented on ConfirmInput/README.md
> +    prompt: bytes
[confirm_input.tar.gz](https://github.com/tonlabs/DeBot-IS-consortium/files/5981436/confirm_input.tar.gz)

ConfirmInput.sol
ConfirmInput.abi.json
ConfirmInput.hpp
Example.sol

2021-02-15 12:11 UTC, Keshoid commented on ConfirmInput/README.md
> +TODO: Add declaration
```suggestion
interface IConfirmInput {

	function select(uint32 answerId, string prompt) external returns (bool value);

}
```

2021-02-15 12:11 UTC, Keshoid commented on ConfirmInput/README.md
> +TODO: Add declaration
```suggestion
namespace tvm { namespace schema {

__interface IConfirmInput {
	[[internal, answer_id]]
	bool_t select(string prompt);
}

}};
```

2021-02-15 12:11 UTC, Keshoid commented on ConfirmInput/README.md
> +TODO: Add example
```suggestion
Example.sol
```

2021-02-16 09:03 UTC, Keshoid approved these changes

2021-02-16 09:49 UTC, sertony approved these changes

2021-02-16 13:11 UTC, mikhailUshakoff approved these changes

2021-02-16 13:29 UTC, mikhailUshakoff commented on ConfirmInput/ConfirmInput.sol
> +	function select(uint32 answerId, string prompt) external returns (bool value);
rename to get

2021-02-17 18:29 UTC, azhogin approved these changes

2021-02-20 13:54 UTC, merged