Add DateInput interface
tonlabs/DeBot-IS-consortium pull request #18
Opened 2021-02-10 18:15 UTC by BigRoma

2021-02-12 12:29 UTC, sertony requested changes

2021-02-12 12:29 UTC, sertony commented on DateInput/README.md
> +    min: uint32
Date can a have a negative timestamp

2021-02-12 12:29 UTC, sertony commented on DateInput/README.md
> +    exclude: uint32[]
If you exclude the date, you exclude the range or an array of ranges, not an array of values.

2021-02-12 12:29 UTC, sertony commented on DateInput/README.md
> +    exclude: uint32[]
Actually if you have an exclude here you cannot guaranty the solid range...

I'd consider removing the `exclude` argument for now in both methods, but we might need to discuss together.

2021-02-12 12:56 UTC, Keshoid reviewed
My suggestion:
rename iface to `DateTimeInput`.
remove `exclude` - it complicates the interface and has some corners.
return not just a `uint32` value but a struct with info about time:
```
struct DateTime {
 uint16 year;
uint8 month;
uint8 day;
uint8 hours;
uint8 minutes;
uint8 seconds;
int32 unixtime;
}

```

2021-02-15 08:51 UTC, BigRoma commented
> My suggestion:
> rename iface to `DateTimeInput`.
> remove `exclude` - it complicates the interface and has some corners.
> return not just a `uint32` value but a struct with info about time:
> 
> ```
> struct DateTime {
>  uint16 year;
> uint8 month;
> uint8 day;
> uint8 hours;
> uint8 minutes;
> uint8 seconds;
> int32 unixtime;
> }
> ```

Ok, but I don't understand why we must add unix time, it doesn't match with answer structure, because we can set only date, but don't set time. I think we need three methods: date, dateTime, time, that return  different answers type.

2021-05-13 21:50 UTC, NoamDev commented
> My suggestion:
> rename iface to `DateTimeInput`.
> remove `exclude` - it complicates the interface and has some corners.
> return not just a `uint32` value but a struct with info about time:
> 
> ```
> struct DateTime {
>  uint16 year;
> uint8 month;
> uint8 day;
> uint8 hours;
> uint8 minutes;
> uint8 seconds;
> int32 unixtime;
> }
> ```

years should be a signed integer.

2021-07-05 16:43 UTC, closed without merging