add NaclBox interface
tonlabs/DeBot-IS-consortium pull request #27
Opened 2021-03-22 08:59 UTC by mikhailUshakoff

2021-03-22 11:21 UTC, sertony requested changes

2021-03-22 11:21 UTC, sertony commented on NaclBox/README.md
> +`getPublicKey` - get curve256 public key from signing box handle.
Maybe we are to rename it to make it more clear (to identify this public key is supposed to be used for the encryption)? e.g. `getEncryptPublicKey`

2021-03-22 11:21 UTC, sertony commented on NaclBox/README.md
> +        publicKey: uint256 - handle to signing box
Or, rename this parameter instead, e.g. `signPublicKey`

2021-03-22 11:21 UTC, sertony commented on NaclBox/README.md
> +        publicKey: uint256 - handle to signing box
Maybe like this?
```
        theirEncryptPublicKey: uint256 - receiver's public key
        signPublicKey: uint256 - handle to signing box
```

2021-03-22 11:21 UTC, sertony commented on NaclBox/README.md
> +        publicKey: uint256 - handle to signing box
Same concern about naming, i.e.
```
        theirEncryptPublicKey: uint256 - receiver's public key
        signPublicKey: uint256 - handle to signing box
```

2021-03-22 11:21 UTC, sertony commented on NaclBox/README.md
> +	function getPublicKey(uint32 answerId, uint256 publicKey) external returns (uint256 publicKey);
```suggestion
	function getEncryptPublicKey(uint32 answerId, uint256 signPublicKey) external returns (uint256 encryptPublicKey);
```

2021-03-22 11:21 UTC, sertony commented on NaclBox/README.md
> +	function encrypt(uint32 answerId, bytes decrypted, bytes nonce, uint256 their_public, uint256 publicKey) external returns (bytes encrypted, uint256 publicKey);
```suggestion
	function encrypt(uint32 answerId, bytes decrypted, bytes nonce, uint256 theirEncryptPublicKey, uint256 signPublicKey) external returns (bytes encrypted, uint256 encryptPublicKey);
```

2021-03-22 11:21 UTC, sertony commented on NaclBox/README.md
> +	function decrypt(uint32 answerId, bytes encrypted, bytes nonce, uint256 their_public, uint256 publicKey) external returns (bytes decrypted);
```suggestion
	function decrypt(uint32 answerId, bytes encrypted, bytes nonce, uint256 theirEncryptPublicKey, uint256 signPublicKey) external returns (bytes decrypted);
```

2021-03-22 11:21 UTC, sertony commented on NaclBox/README.md
> +	pubkey: uint256 - curve256 public key deduce from signing box keys
```
	encryptPublicKey: uint256 - curve256 public key deduce from signing box keys
```

2021-03-22 11:21 UTC, sertony commented on NaclBox/README.md
> +	pubkey: uint256 - curve256 public key deduce from signing box keys
```
	encryptPublicKey: uint256 - curve256 public key deduce from signing box keys
```

2021-03-29 11:29 UTC, sertony approved these changes

2021-04-22 10:57 UTC, Keshoid commented on NaclBox/NaclBox.sol
> +	uint256 constant DEBOT_ADDR = da6e573c0282785d9f8e88a81e0f2665811148cb3bd9b5dcce6a079ab7009958;
Can you rename it to `ID`? it is better to use `ID` in `getRequiredInterfaces` like `[... , NaclBox.ID]`

2021-04-27 06:47 UTC, Keshoid requested changes
Please, make example DeBot from example contract.

2021-05-20 08:54 UTC, sertony requested changes
I also have some doubts about a possibility to derive the encryption public key (Nacl) for any signing box handle

2021-05-20 08:54 UTC, sertony commented on NaclBox/NaclBox.sol
> +	function getPublicKey(uint32 answerId, uint32 edHandle) public pure {
```suggestion
	function getEncryptPublicKey(uint32 answerId, uint32 edHandle) public pure {
```

2021-05-20 08:58 UTC, sertony commented
I guess that it's better to work with EncryptionBox handle instead of SigningBox handles
https://www.notion.so/tonlabs/Crypto-Boxes-in-Core-79c05b38d231482a91ace893d8701747#ace7d561f83943c2a66f49ef40b92a7b

But the problem is that we don't have Encryption Boxes in SDK yet =\

2021-06-23 08:40 UTC, closed without merging