Update mandatory info.
tonlabs/DeBot-IS-consortium pull request #32
Opened 2021-04-12 14:29 UTC by BigRoma

2021-04-12 20:22 UTC, Keshoid approved these changes
Ok

2021-04-13 10:15 UTC, sauin commented on MandatoryDeBotFunctions.md
> +    caption: bytes - (10-20 ch.) utf-8 string with short description, e.g. "Work with DePools"
Debot.sol still has the `key` param

2021-04-13 10:15 UTC, sauin commented on MandatoryDeBotFunctions.md
> +
Missing `dabi` and `icon` parameters

2021-04-16 08:07 UTC, BigRoma commented on MandatoryDeBotFunctions.md
> +    caption: bytes - (10-20 ch.) utf-8 string with short description, e.g. "Work with DePools"
Yep, we will change it after PR merge.

2021-04-21 06:19 UTC, sauin approved these changes

2021-04-26 06:46 UTC, Keshoid approved these changes

2021-04-26 06:46 UTC, Keshoid commented on MandatoryDeBotFunctions.md
> +        function getInfo() override returns (string name, string version, string publisher, string key, string author, address support, string hello, string language) {
```suggestion
        function getDebotInfo() public functionID(0xDEB) view override returns(
        string name, string version, string publisher, string caption, string author,
        address support, string hello, string language, string dabi, bytes icon) {
```

2021-04-26 06:46 UTC, Keshoid commented on MandatoryDeBotFunctions.md
> +    icon: bytes - base64 encoded PNG image (144x144 px)
```suggestion
    icon: bytes - base64 encoded PNG image (144x144 px)
```
```suggestion
    icon: bytes - utf8-string with encoded PNG image (144x144 px). The string format is "data:image/png;base64,<image>", where `image` - image bytes encoded in base64. See example below.
```

2021-04-27 06:56 UTC, Keshoid requested changes
Please, apply suggestions.

2021-04-29 20:27 UTC, Keshoid approved these changes

2021-04-29 20:27 UTC, merged