add ComboBoxInput interface
tonlabs/DeBot-IS-consortium pull request #67
Opened 2021-10-12 07:47 UTC by mikhailUshakoff

2021-10-12 08:27 UTC, BigRoma commented on ComboBoxInput/README.md
> +    items: bytes[] - list of items for selection. (should not be reshuffled by a browser)
I think we need a structure, in this case, for example, we can select a country and get value like "RU", but normally our need to show the name of the country, like "Russia". 

```
struct ComboBoxItem {
    string label;
    string value;
    bool disabled;
}
```

2021-10-12 08:30 UTC, BigRoma commented on ComboBoxInput/README.md
> +    index: uint256 - index of selected item
Also, we can return more variants than one.

2021-10-12 08:34 UTC, BigRoma commented on ComboBoxInput/README.md
> +    index: uint256 - index of selected item
If we will use this case, our need the `bool multiple` property in inputs section

2021-10-12 11:31 UTC, BigRoma requested changes
Request changes

2022-01-28 10:00 UTC, ilyar commented
@mikhailUshakoff up

2022-02-14 10:11 UTC, closed without merging