add helper for run examples
tonlabs/DeBot-IS-consortium pull request #77
Opened 2022-06-03 14:18 UTC by ilyar

2022-06-13 09:25 UTC, Keshoid requested changes

2022-06-13 09:25 UTC, Keshoid commented on README.md
> +src=../Sdk/examples bash ../script/debot-run.sh
Sdk is a DEngine built-in interface, not a browser interface

2022-06-13 09:25 UTC, Keshoid commented on README.md
> +**in cli-browser `everos-cli`**
Why do you split interfaces? `cli` and `not cli`.

2022-06-13 09:25 UTC, Keshoid commented on README.md
> +src=../Network/examples bash ../script/debot-run.sh
Base64, Hex, Json, Network are built-in interafces in DEngine.

2022-06-13 09:25 UTC, Keshoid commented on README.md
> +npx everdev sol update
it works without npx. I think, you can delete it everywhere

2022-06-13 09:25 UTC, Keshoid commented on script/debot-run.sh
> +  path="tonlabs/ton-labs-contracts/${rev}/solidity"
Switch to https://github.com/EverSurf/contracts/tree/main/surfmultisig

2022-06-13 09:25 UTC, Keshoid commented on script/debot-run.sh
> +npx tonos-cli debot --debug fetch "${appAddr}"
It's better to run without `--debug`.

2022-06-13 09:34 UTC, Keshoid commented on README.md
> +src=../AddressInput/examples bash ../script/debot-run.sh
What is `current dir` for running this script? I suppose we should run it from repo root dir.

2022-06-13 13:56 UTC, Keshoid requested changes

2022-06-13 13:56 UTC, Keshoid commented on README.md
> +npx everdev network giver se 0:b5e9240fc2d2f1ff8cbb1d1dee7fb7cae155e5f6320e585fcc685698994a19a5 --signer giver
Failed to run this cmd. everdev 1.1.1

2022-06-13 13:56 UTC, Keshoid commented on README.md
> +npx everdev signer default coder
What is coder?

2022-06-14 01:01 UTC, ilyar commented on script/debot-run.sh
> +npx tonos-cli debot --debug fetch "${appAddr}"
nice try)))

2022-06-28 17:44 UTC, closed without merging